name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ZNotify/py-sdk'

      - uses: ZNotify/test-action@master

      - name: Install poetry
        run: pipx install poetry

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install poetry with new python
        run: pip install poetry

      - name: Install dependencies
        run: python -m poetry install

      - name: Test
        run: python -m poetry run python -m unittest discover
